version: 0.2

phases:
  install:
    commands:
      - echo Installing
  pre_build:
    commands:
      - cd .lambda
      - aws cloudformation package --template-file template.yaml --s3-bucket app-dcj-lambda --output-template-file template.yaml  
  build:
    commands:
      - echo Build started on `date`
artifacts:
  type: zip
  files:
    - template.yaml
  